# Capstone Project

## Neighbourhood Analysis for City of Toronto

## Summary:
This notebook will be used for Capstone Project for "IBM Data Science Professional Certificate" course on coursera. Location data is analysed to gain insights on the neighbourhoods in the specified area. In this notebook, we will explore, segment, and cluster the neighbourhoods in the city of <b>Toronto</b>.

In [46]:
#import required libraries
import pandas as pd
import numpy as np

In [47]:
print ("Hello Capstone Project Course!")

Hello Capstone Project Course!

### Capture neighbourhoods in the city of Toronto
Neighborhood details for the city of Torontaby are available on it's wiki page <a>https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M</a>.
We need to scrape the wiki page and extract required information from it.

In [48]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

df = pd.read_html(url, match='Postcode', header=0)[0] # read an html table that contains 'Postcode' and load it into a dataframe
print (df.shape)
df.head()

(287, 3)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

### Preprocess data

In [49]:
#Only process the cells that have an assigned Borough. Ignore cells with a borough that is Not assigned.
df['Borough'].replace('Not assigned', np.nan, inplace=True) # replace 'Not assigned' with NAN
df.dropna(axis=0, inplace=True) # drop rows where NAN
print (df.shape)
df.head()

(210, 3)

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor

In [51]:
#More than one neighborhood can exist in one postal code area
#Combine neighbourhood with comma for each postal code. 
#Use Groupby on Postcode and Borough and apply String join function on Neigbourhood (Refer w3schools python string join tutorial)
df = df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
print (df.shape)
df.head()

(103, 3)

  Postcode      Borough                         Neighbourhood
0      M1B  Scarborough                         Rouge,Malvern
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough       Guildwood,Morningside,West Hill
3      M1G  Scarborough                                Woburn
4      M1H  Scarborough                             Cedarbrae

In [52]:
#If a cell has a Borough but a Not assigned Neighborhood, then the Neighborhood will be the same as the borough
df['Neighbourhood'].replace('Not assigned', np.nan, inplace=True) # replace 'Not assigned' with NAN
df['Neighbourhood'].fillna(df['Borough'], inplace=True) # Replace with Borough
df.head()

  Postcode      Borough                         Neighbourhood
0      M1B  Scarborough                         Rouge,Malvern
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough       Guildwood,Morningside,West Hill
3      M1G  Scarborough                                Woburn
4      M1H  Scarborough                             Cedarbrae

In [59]:
print ('The Neighbourhood dataframe has {} number of rows'.format(df.shape[0]))

The Neighbourhood dataframe has 103 number of rows